apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: QSD-data
  namespace: QSD
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Change based on your cluster

