//go:build !cgo || dilithium_circl
// +build !cgo dilithium_circl

package crypto

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"errors"
	"testing"

	"github.com/cloudflare/circl/sign/mldsa/mldsa87"
)

// Stage A test suite for the cloudflare/circl pure-Go ML-DSA-87
// backend. These tests run only under `-tags dilithium_circl`,
// matching the build tag that selects the backend itself, so the
// default non-CGO build is unaffected.
//
// The tests fall into four buckets, each guarding a distinct
// production invariant:
//
//  1. Wire-format compliance with FIPS 204 §6.1 (key + signature
//     byte sizes), which is also the contract pkg/chain/txsig.go's
//     length-prefixed verifier already enforces. Drift here would
//     desync the chain from the on-wire envelope.
//
//  2. Round-trip correctness: keys generated by NewDilithium can
//     sign messages and the resulting signature verifies under
//     both the same handle (Verify) and an externally-supplied
//     copy of the public key (VerifyWithPublicKey). This is the
//     happy path the wallet and PoE backends exercise.
//
//  3. Tamper-detection negatives: a valid signature must fail
//     verification when the message, the signature, or the
//     public key is mutated. Without these the backend could
//     trivially accept bogus inputs and the consensus path
//     would silently fork from a CGO+liboqs binary.
//
//  4. API-shape compatibility with the CGO+liboqs backend:
//     NewDilithiumVerifyOnly returns a non-nil handle whose Sign
//     yields ErrSignVerifyOnly, Free is a no-op, and the
//     pkg/chain/txsig.go length constants match the circl
//     constants byte-for-byte.

// TestCircl_FIPS204_SizesMatchTxsigConstants is the byte-exact
// FIPS 204 §6.1 tripwire. pkg/chain/txsig.go encodes both the
// public key length (2592) and the signature length (4627) as
// untyped constants in the verifier; if circl's compile-time
// constants ever drift from those values (or vice versa), the
// chain would either reject every signature or accept malformed
// envelopes. Catching the drift here, in the same package as the
// backend, is cheaper than a runtime mismatch in production.
func TestCircl_FIPS204_SizesMatchTxsigConstants(t *testing.T) {
	const (
		txsigPublicKeyLen = 2592
		txsigSignatureLen = 4627
	)
	if mldsa87.PublicKeySize != txsigPublicKeyLen {
		t.Errorf("ML-DSA-87 PublicKeySize: circl reports %d, pkg/chain/txsig.go expects %d (FIPS 204 §6.1 fixes this at 2592)",
			mldsa87.PublicKeySize, txsigPublicKeyLen)
	}
	if mldsa87.SignatureSize != txsigSignatureLen {
		t.Errorf("ML-DSA-87 SignatureSize: circl reports %d, pkg/chain/txsig.go expects %d (FIPS 204 §6.1 fixes this at 4627)",
			mldsa87.SignatureSize, txsigSignatureLen)
	}
}

// TestCircl_RoundTrip_NewDilithium covers the Stage A happy path:
// NewDilithium generates a keypair, Sign produces a wire-sized
// signature, and Verify returns true. Verify is the consensus-
// critical primitive; Sign is exercised here only as the source
// of a known-good signature for the verifier to consume.
func TestCircl_RoundTrip_NewDilithium(t *testing.T) {
	d := NewDilithium()
	if d == nil {
		t.Fatal("NewDilithium returned nil — entropy source unavailable?")
	}
	defer d.Free()

	msg := []byte("QSD circl-backend round-trip canary message")
	sig, err := d.Sign(msg)
	if err != nil {
		t.Fatalf("Sign: %v", err)
	}
	if got, want := len(sig), mldsa87.SignatureSize; got != want {
		t.Fatalf("signature length: got %d, want %d", got, want)
	}

	ok, err := d.Verify(msg, sig)
	if err != nil {
		t.Fatalf("Verify: %v", err)
	}
	if !ok {
		t.Fatal("Verify on a freshly-signed message returned false; backend is broken")
	}
}

// TestCircl_VerifyWithPublicKey_ExternalPK covers the pkg/chain/
// txsig.go consensus path: the verifier is handed the public key
// out-of-band (from the SignedTx envelope) and must produce the
// same accept/reject answer as a same-handle Verify. This is the
// path every node runs against every transaction; bugs here are
// fork-class.
func TestCircl_VerifyWithPublicKey_ExternalPK(t *testing.T) {
	d := NewDilithium()
	if d == nil {
		t.Fatal("NewDilithium returned nil")
	}
	defer d.Free()

	pkBytes, err := d.verifyKey.MarshalBinary()
	if err != nil {
		t.Fatalf("MarshalBinary: %v", err)
	}
	if got, want := len(pkBytes), mldsa87.PublicKeySize; got != want {
		t.Fatalf("packed public key length: got %d, want %d", got, want)
	}

	msg := []byte("verifyWithPublicKey external-key happy path")
	sig, err := d.Sign(msg)
	if err != nil {
		t.Fatalf("Sign: %v", err)
	}

	verifier := NewDilithiumVerifyOnly()
	ok, err := verifier.VerifyWithPublicKey(msg, sig, pkBytes)
	if err != nil {
		t.Fatalf("VerifyWithPublicKey: %v", err)
	}
	if !ok {
		t.Fatal("VerifyWithPublicKey returned false on a known-good (msg, sig, pk) triple")
	}
}

// TestCircl_TamperDetection guards the rejection invariants. We
// produce one known-good (msg, sig, pk) triple, then mutate each
// component independently and assert the verifier rejects each
// mutation. Any pass-through here is a forge-acceptance bug.
func TestCircl_TamperDetection(t *testing.T) {
	d := NewDilithium()
	if d == nil {
		t.Fatal("NewDilithium returned nil")
	}
	defer d.Free()

	pkBytes, err := d.verifyKey.MarshalBinary()
	if err != nil {
		t.Fatalf("MarshalBinary: %v", err)
	}
	msg := []byte("tamper-detection canary")
	sig, err := d.Sign(msg)
	if err != nil {
		t.Fatalf("Sign: %v", err)
	}

	verifier := NewDilithiumVerifyOnly()

	// Sanity: known-good triple verifies.
	if ok, err := verifier.VerifyWithPublicKey(msg, sig, pkBytes); err != nil || !ok {
		t.Fatalf("baseline VerifyWithPublicKey: ok=%v err=%v", ok, err)
	}

	t.Run("mutated_message", func(t *testing.T) {
		bad := append([]byte{}, msg...)
		bad[0] ^= 0x01
		ok, err := verifier.VerifyWithPublicKey(bad, sig, pkBytes)
		if err != nil {
			t.Fatalf("err on mutated msg: %v", err)
		}
		if ok {
			t.Fatal("mutated message verified true; signature must be rejected")
		}
	})

	t.Run("mutated_signature", func(t *testing.T) {
		bad := append([]byte{}, sig...)
		// Flip a bit deep inside the c~ component (first 64
		// bytes of the encoded signature). This region is the
		// FIPS 204 c-tilde commitment hash; any flip there
		// must produce verify=false.
		bad[10] ^= 0x80
		ok, err := verifier.VerifyWithPublicKey(msg, bad, pkBytes)
		if err != nil {
			t.Fatalf("err on mutated sig: %v", err)
		}
		if ok {
			t.Fatal("mutated signature verified true; verifier is broken")
		}
	})

	t.Run("mutated_public_key", func(t *testing.T) {
		bad := append([]byte{}, pkBytes...)
		// Flip a bit in the t1 vector encoding (after the
		// 32-byte rho prefix). Any non-zero flip must produce
		// verify=false against the original (msg, sig).
		bad[200] ^= 0x01
		ok, err := verifier.VerifyWithPublicKey(msg, sig, bad)
		// Mutating a public key may make it cryptographically
		// invalid (verify=false) OR structurally invalid
		// (UnmarshalBinary error). Either is fine — the contract
		// is "do not verify true under a key the signer didn't
		// authorise". Some encodings are tolerant of bit flips
		// in dead-padding regions, in which case ok=false is
		// the only acceptable outcome.
		if err == nil && ok {
			t.Fatal("mutated public key verified true; verifier is accepting unauthorised keys")
		}
	})
}

// TestCircl_VerifyOnly_HandleSemantics covers the API-shape
// invariant the CGO+liboqs backend established: a handle made
// via NewDilithiumVerifyOnly has no signing material, Sign on it
// returns ErrSignVerifyOnly, and Free is a no-op (no panic).
// Without these guards downstream code that does
// `defer d.Free()` and falls into a sign path would silently
// forge invalid output in the pure-Go backend.
func TestCircl_VerifyOnly_HandleSemantics(t *testing.T) {
	v := NewDilithiumVerifyOnly()
	if v == nil {
		t.Fatal("NewDilithiumVerifyOnly returned nil; pure-Go backend should always return non-nil")
	}
	if v.signKey != nil {
		t.Error("verify-only handle has a non-nil signKey; signing material leaked")
	}
	if v.verifyKey != nil {
		t.Error("verify-only handle has a non-nil verifyKey; pure-Go backend should leave it nil until VerifyWithPublicKey supplies one")
	}

	if _, err := v.Sign([]byte("anything")); !errors.Is(err, ErrSignVerifyOnly) {
		t.Errorf("Sign on verify-only: got %v, want errors.Is(err, ErrSignVerifyOnly)", err)
	}

	// Free must be a no-op safety net so downstream
	// `defer d.Free()` is sound under both backends.
	v.Free()
}

// TestCircl_StubFlagNotMarked guards the operational invariant
// that, under the dilithium_circl tag, the stub-active flag for
// kind="dilithium" stays at 0 — the whole point of Stage A is
// that the kind is no longer a stub on this build path. The
// dilithium_stub.go init() is excluded by build tag, so no test-
// time MarkActive should ever fire for KindDilithium.
//
// We import stubactive lazily through a helper to avoid pulling
// in the monitoring tree on tag-off builds; the import is
// already present in dilithium_stub.go on the off path so the
// dependency exists either way.
func TestCircl_StubFlagNotMarked(t *testing.T) {
	// Constructing the backend should not flip any flag.
	d := NewDilithium()
	if d == nil {
		t.Fatal("NewDilithium returned nil")
	}
	defer d.Free()

	if got := stubActiveDilithiumIsActive(); got {
		t.Errorf("QSD_stub_active{kind=\"dilithium\"} unexpectedly true under -tags dilithium_circl; the stub init() is supposed to be excluded by build tag")
	}
}

// TestCircl_DeterministicRecovery_FromSeed exercises the
// NewKeyFromSeed path circl exposes for fixture generation.
// The test asserts that signing a known message with a key
// derived from a fixed seed produces a wire-sized signature
// and that the same key recovered from the seed in a later
// invocation verifies it — the foundation any future inter-
// backend KAT vector parity test would build on.
func TestCircl_DeterministicRecovery_FromSeed(t *testing.T) {
	var seed [mldsa87.SeedSize]byte
	if _, err := rand.Read(seed[:]); err != nil {
		t.Fatalf("rand.Read seed: %v", err)
	}

	pk1, sk1 := mldsa87.NewKeyFromSeed(&seed)
	d1 := &Dilithium{signKey: sk1, verifyKey: pk1}
	defer d1.Free()

	msg := []byte("seed-deterministic round-trip")
	sig, err := d1.Sign(msg)
	if err != nil {
		t.Fatalf("Sign: %v", err)
	}

	// Re-derive the keypair from the same seed. The recovered
	// public key MUST byte-equal the original; that's the
	// FIPS 204 deterministic-keygen contract.
	pk2, _ := mldsa87.NewKeyFromSeed(&seed)
	pkBytes1, err := pk1.MarshalBinary()
	if err != nil {
		t.Fatalf("pk1 MarshalBinary: %v", err)
	}
	pkBytes2, err := pk2.MarshalBinary()
	if err != nil {
		t.Fatalf("pk2 MarshalBinary: %v", err)
	}
	if !bytes.Equal(pkBytes1, pkBytes2) {
		t.Fatal("public keys derived from the same seed differ; FIPS 204 keygen is supposed to be deterministic")
	}

	// And the recovered key verifies a signature produced
	// with the original.
	verifier := NewDilithiumVerifyOnly()
	ok, err := verifier.VerifyWithPublicKey(msg, sig, pkBytes2)
	if err != nil {
		t.Fatalf("VerifyWithPublicKey: %v", err)
	}
	if !ok {
		t.Fatal("recovered public key failed to verify signature from twin private key")
	}
}

// TestCircl_AddressBindingMatchesTxsig confirms the SHA-256(pk)
// → wallet-style address binding pkg/chain/txsig.go enforces is
// invariant under the choice of signature backend. A mismatch
// would block circl-built nodes from seeing the same sender
// addresses CGO+liboqs nodes see, even though both backends
// produce byte-identical wire-format public keys.
func TestCircl_AddressBindingMatchesTxsig(t *testing.T) {
	d := NewDilithium()
	if d == nil {
		t.Fatal("NewDilithium returned nil")
	}
	defer d.Free()

	pkBytes, err := d.verifyKey.MarshalBinary()
	if err != nil {
		t.Fatalf("MarshalBinary: %v", err)
	}
	addr := sha256.Sum256(pkBytes)
	if len(addr) != 32 {
		t.Fatalf("SHA-256 address length: got %d, want 32", len(addr))
	}
	// We don't compare against a fixture (each test run
	// generates a fresh key); the assertion is structural —
	// the address derivation is total, hash output is
	// 32 bytes, and the public-key encoding round-trips.
	pkRecovered := new(mldsa87.PublicKey)
	if err := pkRecovered.UnmarshalBinary(pkBytes); err != nil {
		t.Fatalf("UnmarshalBinary on a freshly marshalled key failed: %v", err)
	}
	pkRecoveredBytes, err := pkRecovered.MarshalBinary()
	if err != nil {
		t.Fatalf("re-MarshalBinary: %v", err)
	}
	if !bytes.Equal(pkBytes, pkRecoveredBytes) {
		t.Fatal("public key did not round-trip through Marshal/Unmarshal/Marshal — encoding is non-canonical")
	}
}
